name: Coverity Scan

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  coverity_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Coverity Build Tool
        run: |
          wget --quiet --output-document=coverity_tool.tgz \
          --post-data "token=${{ secrets.COVERITY_TOKEN }}&project=MyTestAnalyzer1" \
          https://scan.coverity.com/download/linux64

      - name: Verify Download
        run: |
          ls -la
          file coverity_tool.tgz

      - name: Extract Coverity Tool
        run: |
          mkdir coverity_tool
          tar -xvzf coverity_tool.tgz -C coverity_tool --strip-components=1

      - name: List Extracted Files
        run: ls -la coverity_tool

      - name: Build with Coverity
        run: |
          chmod +x coverity_tool/bin/cov-build
          coverity_tool/bin/cov-build --dir cov-int make
