name: Coverity Scan

on:
  push:
    branches:
      - main  # Change this to your target branch if needed

jobs:
  coverity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies (if needed)
        run: sudo apt-get install -y build-essential

      - name: Download Coverity Tools
        run: |
          wget https://scan.coverity.com/download/linux64 \
            --post-data "token=8jFSFWivFSIlWhx63uZgDA&project=MyTestAnalyzer1" -O coverity_tool.tgz
          tar -xvzf coverity_tool.tgz
          mv cov-analysis-linux64-* coverity
          echo "$(pwd)/coverity/bin" >> $GITHUB_PATH

      - name: Build and Analyze (for .NET projects)
        run: |
          export PATH=$PWD/coverity/bin:$PATH
          cov-build --dir cov-int dotnet build

      - name: Package Scan Results
        run: tar czvf MyTestAnalyzer1.tgz cov-int

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverity-scan-results
          path: MyTestAnalyzer1.tgz

      - name: Upload Scan Results
        run: |
          curl --form token=8jFSFWivFSIlWhx63uZgDA \
               --form email=felixanvwork@gmail.com \
               --form file=@MyTestAnalyzer1.tgz \
               --form version="1.0" \
               --form description="Automated Coverity Scan from GitHub Actions" \
               https://scan.coverity.com/builds
