name: Coverity Scan

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  coverity_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Coverity Build Tool
        run: |
          wget https://scan.coverity.com/download/linux64 \
          --post-data "token=${{ secrets.COVERITY_TOKEN }}&project=MyTestAnalyzer1" \
          -O coverity_tool.tgz

      - name: Extract Coverity Tool
        run: tar -xvzf coverity_tool.tgz

      - name: Build with Coverity
        run: |
          ./cov-analysis-linux64/bin/cov-build --dir cov-int make

      - name: Package the results
        run: tar czvf cov-int.tar.gz cov-int

      - name: Upload to Coverity Scan
        run: |
          curl --form token=${{ secrets.COVERITY_TOKEN }} \
               --form email=${{ secrets.COVERITY_EMAIL }} \
               --form file=@cov-int.tar.gz \
               --form version="1.0" \
               --form description="Automated scan" \
               https://scan.coverity.com/builds?project=MyTestAnalyzer1
